### PR TITLE
Added Requirements.txt and Fixed Tests

### PR DESCRIPTION
**Pull request by noobed-max**
- #21

### CODE REVIEW

**Review by Tejas-ChandraShekarRaju — CHANGES_REQUESTED** [review]
LGTM. Thanks for the fix @noobed-max.

Can you just check one more thing? in crud.py and main.py you have imported other dependecies as well. shutil and sqllite3 that also should be in the requirements.txt right? See the main idea here is if some other developer downloads the project and runs pip install requirements.txt everything should be setup.

**Comment by Ashish9738** [comment]
I think yeah, we have to add sqlite3,  pydantic, requests to it. Other than that it LGTM and shutil, os, string, random are provide by default in python so i don't think so we should add by default.

**Comment by noobed-max** [comment]
hey so the thing is shutil is standard library of python and the sqlite3 i did look out for it too but according to https://stackoverflow.com/questions/19530974/how-can-i-add-the-sqlite3-module-to-python , as well as i wasnt able to find any package of sqlite3 
so  turns out even thats a built in package of python and as we are just performing basic operations the python package covers that up

**Comment by Tejas-ChandraShekarRaju** [comment]
@noobed-max can you update the PR as @Ashish9738 suggested. ? Before this @Ashish9738 clone the project in seperate folder and see if it starts running just after doing pip install requirements.txt. If yes acknowledge here and I will approve if not suggest the changes.

**Comment by noobed-max** [comment]
Yes we can , as the requirements.txt is part of server we don't require requests in it , and sqlite3 can be skipped don't want to mess with python standard libraries with other same libraries except for that we everything is good to go

**Comment by Tejas-ChandraShekarRaju** [comment]
> Yes we can , as the requirements.txt is part of server we don't require requests in it , and sqlite3 can be skipped don't want to mess with python standard libraries with other same libraries except for that we everything is good to go

In that case. Let @Ashish9738 test the scenario I mentioned. If it starts without a hassle I will approve it and you can merge.

**Comment by Ashish9738** [comment]
Add pytest in requirments, other than everything LGTM.

**Review by Tejas-ChandraShekarRaju — APPROVED** [review]
LGTM

**Pull request merged**
